sudo: false

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

language: node_js

node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"

install:
  - npm install --build-from-source

script:
  # Output useful info for debugging
  - node --version
  - npm --version
  # Run tests
  - npm test
  - tree -I node_modules
