sudo: false

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

language: node_js

node_js:
  - "6"
  - "8"
  - "9"
  # - "10"
  # - "11"

before_install:
  # Get commit message to check if we should publish binary
  - COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
  - export PATH=./node_modules/.bin/:$PATH
  # Figure out if we should publish
  - PUBLISH_BINARY=false
  # If we are building a tag then we need to publish a new binary package
  - if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true; fi;
  # or if we put the string [publish binary] in the commit message
  - if test "${COMMIT_MESSAGE#*'[publish binary]'}" != "$COMMIT_MESSAGE"; then PUBLISH_BINARY=true; fi;
  
# Install scripts. (runs after repo cloning)
install:
  - npm install -g npm@latest
  # Ensure source install works and compiles correctly
  - npm install --build-from-source
  # Run tests
  - npm test

before_script:
  - echo "Publishing native platform Binary Package? ->" $PUBLISH_BINARY
  # if we are publishing for this commit, do it
  - if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp package; fi;
  # cleanup
  - node-pre-gyp clean
  - node-gyp clean

# Post-install test scripts.
script:
  # Output useful info for debugging
  - node --version
  - npm --version
  
after_success:
  # if success then query and display all published binaries
  - node-pre-gyp info
  # OpenCover
  - npm install coveralls
  - nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
