sudo: false

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

language: node_js

node_js:
  - "6"
  - "8"
  - "9"
  # - "10"
  # - "11"

# Install scripts. (runs after repo cloning)
install:
  - npm install -g npm@latest
  - npm install --build-from-source
  # Package node-pre-gyps binary
  - .\node_modules\.bin\node-pre-gyp package
  
# Post-install test scripts.
script:
  # Output useful info for debugging
  - node --version
  - npm --version
  # Run tests
  - npm test
  
after_success:
  - npm install coveralls
  - nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
