sudo: false

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

language: node_js

node_js:
  - "6"
  - "8"
  - "10"
  - "11"

install:
  - npm install -g npm@5.10.0
  - npm install --build-from-source

script:
  # Output useful info for debugging
  - node --version
  - npm --version
  # Run tests
  - npm test
